# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(252, 235)
        Form.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 63, 255), stop:1 rgba(0, 88, 73, 255))")
        self.headingLabel = QtWidgets.QLabel(Form)
        self.headingLabel.setGeometry(QtCore.QRect(0, 10, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        font.setItalic(True)
        self.headingLabel.setFont(font)
        self.headingLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.headingLabel.setScaledContents(False)
        self.headingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headingLabel.setObjectName("headingLabel")
        self.headingLabel_2 = QtWidgets.QLabel(Form)
        self.headingLabel_2.setGeometry(QtCore.QRect(20, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.headingLabel_2.setFont(font)
        self.headingLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.headingLabel_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.headingLabel_2.setScaledContents(False)
        self.headingLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.headingLabel_2.setObjectName("headingLabel_2")
        self.headingLabel_3 = QtWidgets.QLabel(Form)
        self.headingLabel_3.setGeometry(QtCore.QRect(110, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.headingLabel_3.setFont(font)
        self.headingLabel_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.headingLabel_3.setScaledContents(False)
        self.headingLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.headingLabel_3.setObjectName("headingLabel_3")
        self.headingLabel_4 = QtWidgets.QLabel(Form)
        self.headingLabel_4.setGeometry(QtCore.QRect(20, 60, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.headingLabel_4.setFont(font)
        self.headingLabel_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.headingLabel_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.headingLabel_4.setScaledContents(False)
        self.headingLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.headingLabel_4.setObjectName("headingLabel_4")
        self.versionLabel = QtWidgets.QLabel(Form)
        self.versionLabel.setGeometry(QtCore.QRect(110, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.versionLabel.setFont(font)
        self.versionLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.versionLabel.setScaledContents(False)
        self.versionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.headingLabel_5 = QtWidgets.QLabel(Form)
        self.headingLabel_5.setGeometry(QtCore.QRect(20, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.headingLabel_5.setFont(font)
        self.headingLabel_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.headingLabel_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.headingLabel_5.setScaledContents(False)
        self.headingLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.headingLabel_5.setObjectName("headingLabel_5")
        self.versionLabel_2 = QtWidgets.QLabel(Form)
        self.versionLabel_2.setGeometry(QtCore.QRect(110, 80, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.versionLabel_2.setFont(font)
        self.versionLabel_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.versionLabel_2.setScaledContents(False)
        self.versionLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel_2.setObjectName("versionLabel_2")
        self.headingLabel_6 = QtWidgets.QLabel(Form)
        self.headingLabel_6.setGeometry(QtCore.QRect(10, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.headingLabel_6.setFont(font)
        self.headingLabel_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.headingLabel_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.headingLabel_6.setScaledContents(False)
        self.headingLabel_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.headingLabel_6.setObjectName("headingLabel_6")
        self.versionLabel_3 = QtWidgets.QLabel(Form)
        self.versionLabel_3.setGeometry(QtCore.QRect(110, 100, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.versionLabel_3.setFont(font)
        self.versionLabel_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.versionLabel_3.setScaledContents(False)
        self.versionLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel_3.setObjectName("versionLabel_3")
        self.versionLabel_4 = QtWidgets.QLabel(Form)
        self.versionLabel_4.setGeometry(QtCore.QRect(110, 120, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.versionLabel_4.setFont(font)
        self.versionLabel_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.versionLabel_4.setScaledContents(False)
        self.versionLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel_4.setObjectName("versionLabel_4")
        self.versionLabel_5 = QtWidgets.QLabel(Form)
        self.versionLabel_5.setGeometry(QtCore.QRect(110, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.versionLabel_5.setFont(font)
        self.versionLabel_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.versionLabel_5.setScaledContents(False)
        self.versionLabel_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel_5.setObjectName("versionLabel_5")
        self.versionLabel_6 = QtWidgets.QLabel(Form)
        self.versionLabel_6.setGeometry(QtCore.QRect(110, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.versionLabel_6.setFont(font)
        self.versionLabel_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.versionLabel_6.setScaledContents(False)
        self.versionLabel_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel_6.setObjectName("versionLabel_6")
        self.versionLabel_7 = QtWidgets.QLabel(Form)
        self.versionLabel_7.setGeometry(QtCore.QRect(110, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.versionLabel_7.setFont(font)
        self.versionLabel_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.versionLabel_7.setScaledContents(False)
        self.versionLabel_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel_7.setObjectName("versionLabel_7")
        self.versionLabel_8 = QtWidgets.QLabel(Form)
        self.versionLabel_8.setGeometry(QtCore.QRect(110, 200, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.versionLabel_8.setFont(font)
        self.versionLabel_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.versionLabel_8.setScaledContents(False)
        self.versionLabel_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.versionLabel_8.setObjectName("versionLabel_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "About"))
        self.headingLabel.setText(_translate("Form", "About"))
        self.headingLabel_2.setText(_translate("Form", "Created by:"))
        self.headingLabel_3.setText(_translate("Form", "Cajun of Obsidian"))
        self.headingLabel_4.setText(_translate("Form", "Version:"))
        self.versionLabel.setText(_translate("Form", "3.0"))
        self.headingLabel_5.setText(_translate("Form", "Support:"))
        self.versionLabel_2.setText(_translate("Form", "<html><head/><body><p><a href=\"https://github.com/DirtyCajunRice/GreedyBashCounter/issues\"><span style=\" color:#ffffff;\">Github</span></a></p></body></html>"))
        self.headingLabel_6.setText(_translate("Form", "Special Thanks:"))
        self.versionLabel_3.setText(_translate("Form", "(Design)"))
        self.versionLabel_4.setText(_translate("Form", "Alastriona of Obsidian"))
        self.versionLabel_5.setText(_translate("Form", "(Testing)"))
        self.versionLabel_6.setText(_translate("Form", "Raynian of Obsidian"))
        self.versionLabel_7.setText(_translate("Form", "Speekz of Obsidian"))
        self.versionLabel_8.setText(_translate("Form", "Uino of Obsidian"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

