# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(251, 341)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(9999, 9999))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./media/doubloon_ex.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 63, 255), stop:1 rgba(0, 88, 73, 255))")
        self.centralwidget.setObjectName("centralwidget")
        self.piratenameLabel = QtWidgets.QLabel(self.centralwidget)
        self.piratenameLabel.setGeometry(QtCore.QRect(10, 10, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        font.setItalic(True)
        self.piratenameLabel.setFont(font)
        self.piratenameLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.piratenameLabel.setScaledContents(False)
        self.piratenameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.piratenameLabel.setObjectName("piratenameLabel")
        self.pirateoceanLabel = QtWidgets.QLabel(self.centralwidget)
        self.pirateoceanLabel.setGeometry(QtCore.QRect(10, 30, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.pirateoceanLabel.setFont(font)
        self.pirateoceanLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.pirateoceanLabel.setText("")
        self.pirateoceanLabel.setScaledContents(False)
        self.pirateoceanLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pirateoceanLabel.setObjectName("pirateoceanLabel")
        self.lavishlockersLabel = QtWidgets.QLabel(self.centralwidget)
        self.lavishlockersLabel.setGeometry(QtCore.QRect(10, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(False)
        self.lavishlockersLabel.setFont(font)
        self.lavishlockersLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lavishlockersLabel.setScaledContents(False)
        self.lavishlockersLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lavishlockersLabel.setObjectName("lavishlockersLabel")
        self.totallavishlockersLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.totallavishlockersLCD.setGeometry(QtCore.QRect(70, 80, 51, 23))
        self.totallavishlockersLCD.setDigitCount(4)
        self.totallavishlockersLCD.setObjectName("totallavishlockersLCD")
        self.averagelavishlockersLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.averagelavishlockersLCD.setGeometry(QtCore.QRect(70, 110, 51, 23))
        self.averagelavishlockersLCD.setDigitCount(4)
        self.averagelavishlockersLCD.setObjectName("averagelavishlockersLCD")
        self.lastbattlelavishlockersLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.lastbattlelavishlockersLCD.setGeometry(QtCore.QRect(200, 80, 41, 23))
        self.lastbattlelavishlockersLCD.setDigitCount(3)
        self.lastbattlelavishlockersLCD.setObjectName("lastbattlelavishlockersLCD")
        self.thisbattlelavishlockersLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.thisbattlelavishlockersLCD.setGeometry(QtCore.QRect(200, 110, 41, 23))
        self.thisbattlelavishlockersLCD.setDigitCount(3)
        self.thisbattlelavishlockersLCD.setObjectName("thisbattlelavishlockersLCD")
        self.totallavishlockersLabel = QtWidgets.QLabel(self.centralwidget)
        self.totallavishlockersLabel.setGeometry(QtCore.QRect(30, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.totallavishlockersLabel.setFont(font)
        self.totallavishlockersLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.totallavishlockersLabel.setScaledContents(False)
        self.totallavishlockersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totallavishlockersLabel.setObjectName("totallavishlockersLabel")
        self.thisbattlelavishlockersLabel = QtWidgets.QLabel(self.centralwidget)
        self.thisbattlelavishlockersLabel.setGeometry(QtCore.QRect(130, 110, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.thisbattlelavishlockersLabel.setFont(font)
        self.thisbattlelavishlockersLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.thisbattlelavishlockersLabel.setScaledContents(False)
        self.thisbattlelavishlockersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thisbattlelavishlockersLabel.setObjectName("thisbattlelavishlockersLabel")
        self.lastbattlelavishlockersLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastbattlelavishlockersLabel.setGeometry(QtCore.QRect(130, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.lastbattlelavishlockersLabel.setFont(font)
        self.lastbattlelavishlockersLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lastbattlelavishlockersLabel.setScaledContents(False)
        self.lastbattlelavishlockersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastbattlelavishlockersLabel.setObjectName("lastbattlelavishlockersLabel")
        self.averagelavishlockersLabel = QtWidgets.QLabel(self.centralwidget)
        self.averagelavishlockersLabel.setGeometry(QtCore.QRect(10, 110, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.averagelavishlockersLabel.setFont(font)
        self.averagelavishlockersLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.averagelavishlockersLabel.setScaledContents(False)
        self.averagelavishlockersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.averagelavishlockersLabel.setObjectName("averagelavishlockersLabel")
        self.battlesLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.battlesLCD.setGeometry(QtCore.QRect(70, 140, 51, 23))
        self.battlesLCD.setSmallDecimalPoint(False)
        self.battlesLCD.setDigitCount(4)
        self.battlesLCD.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.battlesLCD.setProperty("intValue", 0)
        self.battlesLCD.setObjectName("battlesLCD")
        self.battlesLabel = QtWidgets.QLabel(self.centralwidget)
        self.battlesLabel.setGeometry(QtCore.QRect(20, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.battlesLabel.setFont(font)
        self.battlesLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.battlesLabel.setScaledContents(False)
        self.battlesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.battlesLabel.setObjectName("battlesLabel")
        self.lastshiptitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastshiptitleLabel.setGeometry(QtCore.QRect(10, 180, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.lastshiptitleLabel.setFont(font)
        self.lastshiptitleLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lastshiptitleLabel.setScaledContents(False)
        self.lastshiptitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastshiptitleLabel.setObjectName("lastshiptitleLabel")
        self.thisshiptitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.thisshiptitleLabel.setGeometry(QtCore.QRect(10, 210, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.thisshiptitleLabel.setFont(font)
        self.thisshiptitleLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.thisshiptitleLabel.setScaledContents(False)
        self.thisshiptitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thisshiptitleLabel.setObjectName("thisshiptitleLabel")
        self.lastshipdisplayLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastshipdisplayLabel.setGeometry(QtCore.QRect(70, 180, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.lastshipdisplayLabel.setFont(font)
        self.lastshipdisplayLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.lastshipdisplayLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.lastshipdisplayLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lastshipdisplayLabel.setLineWidth(1)
        self.lastshipdisplayLabel.setScaledContents(False)
        self.lastshipdisplayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastshipdisplayLabel.setObjectName("lastshipdisplayLabel")
        self.thisshipdisplayLabel = QtWidgets.QLabel(self.centralwidget)
        self.thisshipdisplayLabel.setGeometry(QtCore.QRect(70, 210, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(9)
        font.setItalic(True)
        self.thisshipdisplayLabel.setFont(font)
        self.thisshipdisplayLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.thisshipdisplayLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.thisshipdisplayLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.thisshipdisplayLabel.setLineWidth(1)
        self.thisshipdisplayLabel.setScaledContents(False)
        self.thisshipdisplayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thisshipdisplayLabel.setObjectName("thisshipdisplayLabel")
        self.piratestatsButton = QtWidgets.QPushButton(self.centralwidget)
        self.piratestatsButton.setGeometry(QtCore.QRect(10, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        font.setItalic(True)
        self.piratestatsButton.setFont(font)
        self.piratestatsButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.piratestatsButton.setDefault(False)
        self.piratestatsButton.setFlat(False)
        self.piratestatsButton.setObjectName("piratestatsButton")
        self.battlestatsButton = QtWidgets.QPushButton(self.centralwidget)
        self.battlestatsButton.setGeometry(QtCore.QRect(130, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        font.setItalic(True)
        self.battlestatsButton.setFont(font)
        self.battlestatsButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.battlestatsButton.setDefault(False)
        self.battlestatsButton.setFlat(False)
        self.battlestatsButton.setObjectName("battlestatsButton")
        self.brandingLabel = QtWidgets.QLabel(self.centralwidget)
        self.brandingLabel.setGeometry(QtCore.QRect(60, 280, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(6)
        font.setItalic(True)
        self.brandingLabel.setFont(font)
        self.brandingLabel.setStyleSheet("color: rgb(102, 102, 102);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.brandingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.brandingLabel.setObjectName("brandingLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setItalic(True)
        self.menubar.setFont(font)
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setStyleSheet("")
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuPirates = QtWidgets.QMenu(self.menubar)
        self.menuPirates.setObjectName("menuPirates")
        self.menuLogging = QtWidgets.QMenu(self.menubar)
        palette = QtGui.QPalette()
        self.menuLogging.setPalette(palette)
        self.menuLogging.setStyleSheet("")
        self.menuLogging.setObjectName("menuLogging")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        self.actionStop.setObjectName("actionStop")
        self.actionSet_Log_Folder = QtWidgets.QAction(MainWindow)
        self.actionSet_Log_Folder.setObjectName("actionSet_Log_Folder")
        self.actionLoad_Pirates = QtWidgets.QAction(MainWindow)
        self.actionLoad_Pirates.setCheckable(False)
        self.actionLoad_Pirates.setObjectName("actionLoad_Pirates")
        self.actionOverride_Counts = QtWidgets.QAction(MainWindow)
        self.actionOverride_Counts.setObjectName("actionOverride_Counts")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionClear_This_Battle = QtWidgets.QAction(MainWindow)
        self.actionClear_This_Battle.setObjectName("actionClear_This_Battle")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuPirates.addAction(self.actionLoad_Pirates)
        self.menuLogging.addAction(self.actionStart)
        self.menuLogging.addAction(self.actionStop)
        self.menuLogging.addAction(self.actionSet_Log_Folder)
        self.menuOptions.addAction(self.actionOverride_Counts)
        self.menuOptions.addAction(self.actionReset)
        self.menuOptions.addAction(self.actionClear_This_Battle)
        self.menuOptions.addAction(self.actionAbout)
        self.menubar.addAction(self.menuPirates.menuAction())
        self.menubar.addAction(self.menuLogging.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GreedyBashCounter"))
        self.piratenameLabel.setText(_translate("MainWindow", "Pirate Not Set"))
        self.lavishlockersLabel.setText(_translate("MainWindow", "Lavish Lockers"))
        self.totallavishlockersLabel.setText(_translate("MainWindow", "Total"))
        self.thisbattlelavishlockersLabel.setText(_translate("MainWindow", "This Battle"))
        self.lastbattlelavishlockersLabel.setText(_translate("MainWindow", "Last Battle"))
        self.averagelavishlockersLabel.setText(_translate("MainWindow", "Average"))
        self.battlesLabel.setText(_translate("MainWindow", "Battles"))
        self.lastshiptitleLabel.setText(_translate("MainWindow", "Last Ship"))
        self.thisshiptitleLabel.setText(_translate("MainWindow", "This Ship"))
        self.lastshipdisplayLabel.setText(_translate("MainWindow", "None"))
        self.thisshipdisplayLabel.setText(_translate("MainWindow", "None"))
        self.piratestatsButton.setText(_translate("MainWindow", "Pirate Stats"))
        self.battlestatsButton.setText(_translate("MainWindow", "Battle Stats"))
        self.brandingLabel.setText(_translate("MainWindow", "Created by Cajun of Obsidian"))
        self.menuPirates.setTitle(_translate("MainWindow", "Pirates"))
        self.menuLogging.setTitle(_translate("MainWindow", "Logging"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionSet_Log_Folder.setText(_translate("MainWindow", "Set Log Folder"))
        self.actionLoad_Pirates.setText(_translate("MainWindow", "Load Pirates"))
        self.actionOverride_Counts.setText(_translate("MainWindow", "Override"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionClear_This_Battle.setText(_translate("MainWindow", "Clear This Battle"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

